name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CLOUDFLARE_API_TOKEN
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy to Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "3.75.0"
          # command: pages deploy .svelte-kit/cloudflare --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
